"""Dump all parameters via UDP (MAVProxy bridging).

Connects to udp:127.0.0.1:14550 (where MAVProxy forwards COM58 traffic).
Sends PARAM_REQUEST_LIST and saves all PARAM_VALUE responses
to baseline.parm in Mission Planner format.
"""
import sys
import time
from pymavlink import mavutil

DEST = "udpin:127.0.0.1:14550"
OUTPUT = "baseline.parm"


def main():
    print(f"[CONNECT] {DEST}", flush=True)
    m = mavutil.mavlink_connection(DEST, dialect="ardupilotmega",
                                   source_system=250, source_component=0)
    print("[WAIT] heartbeat (15s)...", flush=True)
    hb = m.wait_heartbeat(timeout=15)
    if not hb:
        print("FAIL: no heartbeat")
        sys.exit(2)
    sysid, compid = m.target_system, m.target_component
    print(f"[OK] sys={sysid} comp={compid} type={mavutil.mavlink.enums['MAV_TYPE'].get(hb.type,'?').name}")

    # Request full param list
    print("[REQUEST] PARAM_REQUEST_LIST", flush=True)
    m.mav.param_request_list_send(sysid, compid)

    params = {}
    expected_total = None
    seen_indices = set()
    t0 = time.time()
    last_received = t0
    PARAM_TIMEOUT = 30.0  # 30s of no new params → consider done
    OVERALL_TIMEOUT = 240.0

    while time.time() - t0 < OVERALL_TIMEOUT:
        msg = m.recv_match(type="PARAM_VALUE", blocking=True, timeout=1.0)
        if msg is None:
            if expected_total and len(params) >= expected_total:
                break
            if time.time() - last_received > PARAM_TIMEOUT:
                print(f"[TIMEOUT] no new params for {PARAM_TIMEOUT}s, stopping",
                      flush=True)
                break
            continue
        pid = msg.param_id
        if isinstance(pid, (bytes, bytearray)):
            pid = pid.decode("ascii", errors="ignore")
        pid = pid.strip("\x00")
        if not pid:
            continue
        if pid in params:
            continue
        params[pid] = {"value": msg.param_value, "type": msg.param_type,
                       "index": msg.param_index, "count": msg.param_count}
        expected_total = msg.param_count
        last_received = time.time()
        if len(params) % 25 == 0:
            print(f"  ... {len(params)}/{expected_total} params",
                  flush=True)

    print(f"\n[DONE] collected {len(params)} params (expected {expected_total})",
          flush=True)

    # Write Mission Planner-format .parm file
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(f"# ArduPilot Param dump\n")
        f.write(f"# Generated by _udp_dump_params.py via MAVProxy/UDP bridge\n")
        f.write(f"# Total: {len(params)} params\n")
        f.write(f"# Date: {time.strftime('%Y-%m-%d %H:%M:%S')}\n")
        for name in sorted(params):
            v = params[name]["value"]
            # ArduPilot .parm format: NAME,value (one per line)
            f.write(f"{name},{v}\n")
    print(f"[SAVED] {OUTPUT}")

    # Quick verification: print key params
    print("\n=== Key params snapshot ===")
    for key in ("SYSID_THISMAV", "FRAME_TYPE", "ARMING_CHECK", "FS_THR_ENABLE",
                "LOG_BACKEND_TYPE", "MOT_PWM_TYPE", "MOT_PWM_FREQ",
                "INS_ACCOFFS_X", "INS_ACCOFFS_Y", "INS_ACCOFFS_Z",
                "INS_ACCSCAL_X", "INS_ACCSCAL_Y", "INS_ACCSCAL_Z",
                "INS_GYROFFS_X", "INS_GYROFFS_Y", "INS_GYROFFS_Z",
                "AHRS_TRIM_X", "AHRS_TRIM_Y", "AHRS_EKF_TYPE",
                "COMPASS_USE", "COMPASS_DEV_ID",
                "SERVO1_FUNCTION", "SERVO3_FUNCTION",
                "GPS1_TYPE", "GPS2_TYPE"):
        v = params.get(key, {}).get("value")
        if v is not None:
            print(f"  {key:20s} = {v}")
        else:
            print(f"  {key:20s} = (missing)")


if __name__ == "__main__":
    main()
