/*
 generated hardware definitions from hwdef.dat - DO NOT EDIT
*/

#pragma once

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif

#define HAL_ESP32_BOARD_NAME "esp32s3-rover-v2-pcb"
#define HAL_INS_DEFAULT HAL_INS_INV2
#define INS_MAX_INSTANCES 1
#define HAL_COMPASS_MAX_SENSORS 1
#define AP_COMPASS_ICM20948_ENABLED 1
#define AP_COMPASS_I2C_BACKEND_DEFAULT_ENABLED 0
#define HAL_PROBE_EXTERNAL_I2C_COMPASSES 0
#define AP_BARO_ENABLED 0
#define HAL_BARO_ALLOW_INIT_NO_BARO 1
#define AP_EXTERNAL_AHRS_ENABLED 0
#define AP_EXTERNAL_AHRS_BNO08X_ENABLED 0
#define AP_EXTERNAL_AHRS_BACKEND_DEFAULT_ENABLED 0
#define AP_EXTERNAL_AHRS_VECTORNAV_ENABLED 0
#define AP_EXTERNAL_AHRS_MICROSTRAIN5_ENABLED 0
#define AP_EXTERNAL_AHRS_MICROSTRAIN7_ENABLED 0
#define AP_EXTERNAL_AHRS_INERTIALLABS_ENABLED 0
#define AP_EXTERNAL_AHRS_SBG_ENABLED 0
#define HAL_AHRS_EKF_TYPE_DEFAULT 3
#define ICM_INT_PIN GPIO_NUM_19
#define HAL_NAVEKF2_AVAILABLE 0
#define HAL_NAVEKF3_AVAILABLE 1
#define HAL_BRD_OPTIONS_DEFAULT 2
#define DEFAULT_SERIAL0_PROTOCOL SerialProtocol_MAVLink2
#define DEFAULT_SERIAL0_BAUD 115200
#define DEFAULT_SERIAL1_BAUD 115200
#define DEFAULT_SERIAL1_PROTOCOL SerialProtocol_GPS
#define GPS_TYPE 1
#define GPS_TYPE2 0
#define AP_GPS_UBLOX_ENABLED 1
#define GPS_MAX_RECEIVERS 2
#define GPS_MAX_INSTANCES 2
#define HAL_NUM_CAN_IFACES 1
#define HAL_ENABLE_DRONECAN_DRIVERS 1
#define AP_DRONECAN_ENABLED 1
#define HAL_CANMANAGER_ENABLED 1
#define HAL_DRONECAN_DNA_ENABLED 1
#define HAL_DRONECAN_SEND_GPS 1
#define HAL_DRONECAN_SEND_COMPASS 1
#define HAL_CAN_RX_QUEUE_SIZE 128
#define HAL_CAN_TX_QUEUE_SIZE 32
#define CAN_STB_PIN GPIO_NUM_38
#define HAL_ESP32_RMT_RX_PIN_NUMBER GPIO_NUM_NC
#define HAL_ESP32_SDMMC 0
#define HAL_ESP32_SDCARD 0
#define HAVE_FILESYSTEM_SUPPORT 1
#define HAL_SCHEDULER_LOOP_RATE 400
#define HAL_SCHEDULER_MAX_THREADS 8
#define HAL_THREAD_STACK_SIZE 16384
#define HAL_WITH_PSRAM 1
#define HAL_PSRAM_HEAP_SIZE (6 * 1024 * 1024)
#define AP_ROVER_ENABLED 1
#define MODE_GUIDED_ENABLED 1
#define MODE_AUTO_ENABLED 1
#define MODE_RTL_ENABLED 1
#define HAL_LOGGING_ENABLED 1
#define HAL_OS_POSIX_IO 1
#define HAL_CONSOLE_ENABLED 1
#define LOGGER_MAVLINK_SUPPORT 1
#define HAL_LOGGING_BACKENDS_DEFAULT 1
#define AP_COMPASS_AK09916_ENABLED 0
#define AP_COMPASS_AK8963_ENABLED 0
#define AP_COMPASS_BMM150_ENABLED 0
#define AP_COMPASS_HMC5843_ENABLED 0
#define AP_COMPASS_LIS3MDL_ENABLED 0
#define AP_COMPASS_QMC5883L_ENABLED 0
#define AP_RANGEFINDER_BACKEND_DEFAULT_ENABLED 0
#define AP_RANGEFINDER_DRONECAN_ENABLED 1
#define AP_BATTERY_INA2XX_ENABLED 1
#define HAL_BATTMON_INA2XX_I2C_ADDR 0x40
#define LORA_PIN_SCK     GPIO_NUM_40
#define LORA_PIN_MISO    GPIO_NUM_39
#define LORA_PIN_MOSI    GPIO_NUM_41
#define LORA_PIN_CS      GPIO_NUM_42
#define LORA_PIN_RST     -1
#define LORA_PIN_BUSY    GPIO_NUM_2
#define LORA_PIN_DIO1    GPIO_NUM_1
#define LORA_FREQ_HZ     433000000
#define LORA_TX_POWER    22
#define LORA_SF          11
#define LORA_BW          500
#define HAL_ESP32_ENABLE_LIGHT_SLEEP 0
#define AP_WIFI_ESP32_ENABLED 0
#define AP_WIFI_ESP32_ENABLED 0
#define MODE_ACRO_ENABLED 0
#define MODE_STEERING_ENABLED 0
#define MODE_CIRCLE_ENABLED 0
#define MODE_SMARTRTL_ENABLED 0
#define MODE_SIMPLE_ENABLED 0
#define MODE_POSHOLD_ENABLED 0
#define NUM_RC_CHANNELS 6
#define AP_RELAY_NUM_RELAYS 2
#define RANGEFINDER_MAX_INSTANCES 2
#define AP_INERTIALSENSOR_HARMONICNOTCH_ENABLED 0
#define AP_FILTER_ENABLED 0
#define AP_PROXIMITY_MAX_INSTANCES 1
#define HAL_UART_NUM_SERIAL_PORTS 4
#define HAL_HAVE_SERIAL3_PARAMS 1
#define HAL_HAVE_SERIAL4_PARAMS 0
#define HAL_HAVE_SERIAL5_PARAMS 0
#define HAL_HAVE_SERIAL6_PARAMS 0
#define HAL_HAVE_SERIAL7_PARAMS 0
#define HAL_HAVE_SERIAL8_PARAMS 0
#define HAL_HAVE_SERIAL9_PARAMS 0
#define AP_AIRSPEED_ENABLED 0
#define AP_ROVER_BALANCEBOT_ENABLED 0
#define AP_WINDVANE_ENABLED 1
#define AP_WINDVANE_NMEA_ENABLED 1
#define DEFAULT_SERIAL2_PROTOCOL SerialProtocol_WindVane
#define DEFAULT_SERIAL2_BAUD 4800
#define DEFAULT_SERIAL3_PROTOCOL SerialProtocol_MAVLink2
#define DEFAULT_SERIAL3_BAUD 57600

// SPI buses table
#define HAL_ESP32_SPI_BUSES \
   { .host=SPI3_HOST, .dma_ch=SPI_DMA_CH_AUTO, .mosi=GPIO_NUM_NC, .miso=GPIO_NUM_NC, .sclk=GPIO_NUM_NC },

// SPI devices table
#define HAL_ESP32_SPI_DEVICES \
   {.name= "dummy", .bus=0, .device=0, .cs=GPIO_NUM_NC, .mode=0, .lspeed=1*MHZ, .hspeed=1*MHZ}

// i2c buses table (V2.1 PCB: ICM+INA shared I2C on IO14/IO21)
#define HAL_ESP32_I2C_BUSES \
   { .port=I2C_NUM_0, .sda=GPIO_NUM_14, .scl=GPIO_NUM_21, .speed=400*KHZ, .internal=true, .soft=false }

// serial devices table
#define HAL_ESP32_UART_DEVICES \
   { .port=UART_NUM_0, .rx=GPIO_NUM_44, .tx=GPIO_NUM_43 },\
   { .port=UART_NUM_1, .rx=GPIO_NUM_18, .tx=GPIO_NUM_17 },\
   { .port=UART_NUM_2, .rx=GPIO_NUM_NC, .tx=GPIO_NUM_NC }
#define HAL_ESP32_RCOUT { GPIO_NUM_12, GPIO_NUM_13, GPIO_NUM_45, GPIO_NUM_47, GPIO_NUM_48, GPIO_NUM_11 }

// No SDSPI configuration
